# Generated by Django 3.1.5 on 2021-01-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('text', models.CharField(max_length=280)),
                ('image_url', models.JSONField()),
                ('likes', models.PositiveIntegerField()),
                ('comments', models.PositiveIntegerField()),
                ('retweets', models.PositiveIntegerField()),
            ],
        ),
    ]
