# Generated by Django 3.1.5 on 2021-01-14 10:03

from django.db import migrations, models
import django.db.models.deletion
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_requestaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaction',
            name='action',
            field=models.CharField(choices=[('CREATE', tweet.models.AdminActions['create']), ('DELETE', tweet.models.AdminActions['delete']), ('UPDATE', tweet.models.AdminActions['update'])], max_length=10),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='tweet_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tweet.tweet'),
        ),
    ]
