# Generated by Django 3.1.5 on 2021-01-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0006_auto_20210114_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', tweet.models.LogActions['view']), ('CREATE', tweet.models.LogActions['create']), ('UPDATE', tweet.models.LogActions['update']), ('DELETE', tweet.models.LogActions['delete'])], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
