# Generated by Django 3.1.5 on 2021-01-14 14:44

from django.db import migrations, models
import tweet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='logs',
            name='current_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='logs',
            name='previous_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(choices=[('CREATE', tweet.utils.LogActions['create']), ('DELETE', tweet.utils.LogActions['delete']), ('UPDATE', tweet.utils.LogActions['update']), ('VIEW', tweet.utils.LogActions['view'])], max_length=10),
        ),
    ]
