# Generated by Django 3.1.5 on 2021-01-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_auto_20210114_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
