# Generated by Django 3.1.5 on 2021-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_tweet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='entity',
            field=models.CharField(default='RequestAction', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='resource_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
