# Generated by Django 3.1.5 on 2021-01-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_auto_20210114_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='previous_state',
        ),
    ]
