# Generated by Django 3.1.5 on 2021-01-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_auto_20210114_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestaction',
            old_name='tweet_id',
            new_name='tweet',
        ),
    ]
