# Generated by Django 3.1.5 on 2021-01-14 19:48

from django.db import migrations, models
import tweet.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_auto_20210114_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[(tweet.utils.LogTypes['audit'], 'AUDIT'), (tweet.utils.LogTypes['action'], 'ACTION'), (tweet.utils.LogTypes['access'], 'ACCESS')], default='ACTION', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(choices=[(tweet.utils.LogActions['create'], 'CREATE'), (tweet.utils.LogActions['delete'], 'DELETE'), (tweet.utils.LogActions['update'], 'UPDATE'), (tweet.utils.LogActions['view'], 'VIEW')], max_length=10),
        ),
    ]
